@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Hrmanager Storage" #F4F6F6{
Class "<<interface>>\nHrmanagerStorage" as HrmanagerStorage
Class JsonHrmanagerStorage
Class JsonSerializableHrmanager
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" HrmanagerStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> HrmanagerStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonHrmanagerStorage .up.|> HrmanagerStorage
JsonHrmanagerStorage ..> JsonSerializableHrmanager
JsonSerializableHrmanager --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
