@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HrmanagerParser" as HrmanagerParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> HrmanagerParser : parseCommand(undo)
activate HrmanagerParser

create UndoCommand
HrmanagerParser -> UndoCommand
activate UndoCommand

UndoCommand --> HrmanagerParser
deactivate UndoCommand

HrmanagerParser --> LogicManager : u
deactivate HrmanagerParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoHrmanager()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
